class SaladData {
  static List<Map<String, dynamic>> allSaladData = [
    {
      'id': 1,
      'title': 'Mexican Salad',
      'price': 12,
      'description':
          'Fresh and flavorful Mexican salad with a mix of vegetables and spices.',
      'discount': 5.6,
      'rating': 4.5,
      'time': 15,
      'average': '5-10',
      'like': false,
      'kcal': 200,
      'thumbnail': "https://example.com/mexican_salad_thumbnail.jpg",
      'image': [],
    },
    {
      'id': 2,
      'title': 'Greek Salad',
      'price': 10,
      'description':
          'Classic Greek salad with tomatoes, cucumbers, olives, and feta cheese.',
      'discount': 0,
      'rating': 4.8,
      'time': 10,
      'average': '5-8',
      'like': false,
      'kcal': 180,
      'thumbnail': "https://example.com/greek_salad_thumbnail.jpg",
      'image': [],
    },

// Add 13 more salad data items

    {
      'id': 1,
      'title': 'Caesar Salad',
      'price': 8,
      'description':
          'Traditional Caesar salad with romaine lettuce, croutons, and Caesar dressing.',
      'discount': 3.2,
      'rating': 4.2,
      'time': 12,
      'average': '5-9',
      'like': false,
      'kcal': 220,
      'thumbnail': "https://example.com/caesar_salad_thumbnail.jpg",
      'image': [],
    },
    {
      'id': 4,
      'title': 'Caprese Salad',
      'price': 11,
      'description':
          'Italian Caprese salad with fresh tomatoes, mozzarella cheese, basil, and balsamic glaze.',
      'discount': 1.5,
      'rating': 4.7,
      'time': 8,
      'average': '4-7',
      'like': false,
      'kcal': 160,
      'thumbnail': "https://example.com/caprese_salad_thumbnail.jpg",
      'image': [],
    },

    {
      'id': 5,
      'title': 'Spinach Salad',
      'price': 9,
      'description':
          'Healthy spinach salad with strawberries, almonds, and balsamic vinaigrette.',
      'discount': 0,
      'rating': 4.6,
      'time': 10,
      'average': '5-8',
      'like': false,
      'kcal': 180,
      'thumbnail': "https://example.com/spinach_salad_thumbnail.jpg",
      'image': [],
    },
    {
      'id': 6,
      'title': 'Nicoise Salad',
      'price': 14,
      'description':
          'French Nicoise salad with tuna, boiled eggs, potatoes, green beans, and olives.',
      'discount': 0,
      'rating': 4.4,
      'time': 20,
      'average': '6-11',
      'like': false,
      'kcal': 250,
      'thumbnail': "https://example.com/nicoise_salad_thumbnail.jpg",
      'image': [],
    },
    {
      'id': 7,
      'title': 'Waldorf Salad',
      'price': 10,
      'description':
          'Classic Waldorf salad with apples, celery, grapes, and walnuts in mayonnaise dressing.',
      'discount': 2,
      'rating': 4.3,
      'time': 10,
      'average': '4-8',
      'like': false,
      'kcal': 190,
      'thumbnail': "https://example.com/waldorf_salad_thumbnail.jpg",
      'image': [],
    },
    {
      'id': 8,
      'title': 'Cobb Salad',
      'price': 13,
      'description':
          'American Cobb salad with lettuce, tomatoes, avocado, bacon, eggs, and blue cheese dressing.',
      'discount': 0,
      'rating': 4.6,
      'time': 15,
      'average': '5-9',
      'like': false,
      'kcal': 280,
      'thumbnail': "https://example.com/cobb_salad_thumbnail.jpg",
      'image': [],
    },
    {
      'id': 9,
      'title': 'Thai Beef Salad',
      'price': 15,
      'description':
          'Spicy Thai beef salad with grilled beef, lettuce, cucumber, and Thai dressing.',
      'discount': 0,
      'rating': 4.9,
      'time': 18,
      'average': '6-12',
      'like': false,
      'kcal': 300,
      'thumbnail': "https://example.com/thai_beef_salad_thumbnail.jpg",
      'image': [],
    },
    {
      'id': 10,
      'title': 'Mediterranean',
      'price': 12,
      'description':
          'Healthy Mediterranean quinoa salad with cherry tomatoes, cucumber, olives, and feta cheese.',
      'discount': 4,
      'rating': 4.7,
      'time': 15,
      'average': '5-10',
      'like': false,
      'kcal': 220,
      'thumbnail':
          "https://example.com/mediterranean_quinoa_salad_thumbnail.jpg",
      'image': [],
    },
    {
      'id': 11,
      'title': 'Couscous Salad',
      'price': 9,
      'description':
          'Light and fluffy couscous salad with roasted vegetables and lemon vinaigrette.',
      'discount': 0,
      'rating': 4.5,
      'time': 12,
      'average': '5-9',
      'like': false,
      'kcal': 190,
      'thumbnail': "https://example.com/couscous_salad_thumbnail.jpg",
      'image': [],
    },
    {
      'id': 12,
      'title': 'Fruit Salad',
      'price': 7,
      'description':
          'Refreshing fruit salad with a mix of seasonal fruits and honey-lime dressing.',
      'discount': 1,
      'rating': 4.3,
      'time': 10,
      'average': '4-8',
      'like': false,
      'kcal': 150,
      'thumbnail': "https://example.com/fruit_salad_thumbnail.jpg",
      'image': [],
    },
  ];
}
